parameters:
  packQA: false
  publishOutput: false

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '24.x'
  displayName: 'Install Node.js'
- script: npm install
  displayName: 'Resolving dependencies'
- task: SonarCloudPrepare@4
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: SonarCloud
    organization: azuredevopsextensions
    scannerMode: CLI
- script: npm run compile
  displayName: 'Building'
- script: npm run package:qa
  displayName: 'Packing extension for QA'
  condition: ${{parameters.packQA}}
- script: npm run package:prod
  displayName: 'Packing extension for Production'
- task: SonarCloudAnalyze@4
  displayName: 'Run Code Analysis'
- task: SonarCloudPublish@4
  displayName: 'Publish Quality Gate Result'
- task: CopyFiles@2
  displayName: Copy vsix files
  condition: ${{parameters.publishOutput}}
  inputs:
    sourceFolder: $(Build.SourcesDirectory)/out
    contents: |
      **/*.vsix
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publishing artifacts'
  condition: ${{parameters.publishOutput}}